name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install zip

      - name: Build ZIP package
        run: bash build.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: Magisk_DNS_Crypt.zip
