name: Build Magisk Module

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ZIP
        run: sudo apt install zip -y

      - name: Create Magisk module ZIP
        run: |
          zip -r -0 doh_client.zip META-INF/ module.prop system/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: doh_client
          path: doh_client.zip